[package]
name = "zk-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ec = "0.4"
ark-ff = "0.4"
ark-secp256k1 = "0.4"
ark-std = "0.4"
ark-bn254 = "0.4"
getrandom = { version = "0.2", features = ["std"] }
num-bigint = "0.4.6"
sha2 = "0.10.9"
ark-poly = "0.4"

[dev-dependencies]
proptest = "1.11.0"
